num_classes: 3
batch_size: 128
num_workers: 8
num_features: 4
num_hidden: 6
num_output: 3
layers_hidden: [4, 128, 128, 64, 64, 32, 32, 3] # best_model_res.pkl
# layers_hidden: [4, 128, 64, 32, 3] # best_model_7503.pkl
epochs: 100
update_grid_interval: 50
learning_rate: 0.001
use_WELL: false
use_DEPTH: true